services:
  #audio-recorder
  audio-recorder:
    build:
      context: https://github.com/raouldeejay/docker-audio-recorder.git
      dockerfile: Dockerfile
    container_name: docker-audio-recorder
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - /mnt/data/audio-recorder:/app/recordings
      - /proc/asound:/mnt/asound:ro
      - /run/user/1000/pulse:/run/user/1000/pulse
    group_add:
      - audio
    devices:
      - /dev/snd:/dev/snd  # Grant access to audio
    environment:
      - FLASK_ENV=production
      - AUDIO_DEVICE=default  # Can be changed to specific device
      - PULSE_SERVER=unix:/run/user/1000/pulse/
    privileged: false
    profiles: [rpi4,rpi5]
