services:
  #audio-recorder
  audio-recorder:
    build:
      context: https://github.com/raouldeejay/docker-audio-recorder.git
      dockerfile: Dockerfile
    container_name: docker-audio-recorder
    ports:
      - "5000:5000"
    volumes:
      - ./recordings:/app/recordings
    devices:
      - /dev/snd:/dev/snd  # Grant access to audio
    environment:
      - FLASK_ENV=production
      - AUDIO_DEVICE=default  # Can be changed to specific device
    privileged: false
